// Parity test: JS port of count_cycles (gee_app/lib/count_cycles.js) vs the
// real Python count_cycles (src/cropint/timeseries/processing.py), compared
// via fixtures generated by scripts/generate_count_cycles_fixtures.py.
//
// Run: node --test gee_app/test/
// The fixture file is NOT generated by this test -- run
// scripts/generate_count_cycles_fixtures.py first.

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const countCyclesLib = require("../lib/count_cycles.js");

const FIXTURE_PATH = path.join(__dirname, "..", "..", "tests", "fixtures", "count_cycles_expected.json");

test("count_cycles JS port matches Python fixtures", async function (t) {
  if (!fs.existsSync(FIXTURE_PATH)) {
    assert.fail(
      "Fixture file not found at " + FIXTURE_PATH +
      " -- run .venv/bin/python scripts/generate_count_cycles_fixtures.py first."
    );
    return;
  }

  const fixture = JSON.parse(fs.readFileSync(FIXTURE_PATH, "utf8"));
  const stepDays = fixture.step_days;
  const peaksCfg = fixture.peaks_cfg;

  for (const point of fixture.points) {
    await t.test(point.name, function () {
      const result = countCyclesLib.countCycles(point.ndvi, stepDays, peaksCfg);
      const expected = point.expected;

      assert.equal(result.classId, expected.class_id, "classId mismatch for " + point.name);
      assert.equal(result.nPeaks, expected.n_peaks, "nPeaks mismatch for " + point.name);

      if (expected.amplitude === null) {
        assert.ok(Number.isNaN(result.amplitude), "amplitude should be NaN for " + point.name);
      } else {
        const diff = Math.abs(result.amplitude - expected.amplitude);
        assert.ok(diff < 1e-6, "amplitude mismatch for " + point.name + ": got " + result.amplitude + ", expected " + expected.amplitude);
      }
    });
  }
});
