// Parity test: JS port of SL2P LAI (gee_app/lib/sl2p_lai.js) vs the real
// Python sl2p_lai_values (src/cropint/gee/biophysical.py), compared via
// fixtures generated by scripts/generate_sl2p_fixtures.py.
//
// Run: node --test gee_app/test/
// The fixture file is NOT generated by this test -- run
// scripts/generate_sl2p_fixtures.py first.

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const sl2pLaiLib = require("../lib/sl2p_lai.js");

const FIXTURE_PATH = path.join(__dirname, "..", "..", "tests", "fixtures", "sl2p_lai_expected.json");

test("sl2p_lai JS port matches Python fixtures", async function (t) {
  if (!fs.existsSync(FIXTURE_PATH)) {
    assert.fail(
      "Fixture file not found at " + FIXTURE_PATH +
      " -- run .venv/bin/python scripts/generate_sl2p_fixtures.py first."
    );
    return;
  }

  const fixture = JSON.parse(fs.readFileSync(FIXTURE_PATH, "utf8"));

  for (const row of fixture.points) {
    await t.test(row.name, function () {
      const got = sl2pLaiLib.sl2pLaiFromInputs(row.inputs);
      const diff = Math.abs(got - row.expected_lai);
      assert.ok(diff < 1e-9, "LAI mismatch for " + row.name + ": got " + got + ", expected " + row.expected_lai);
    });
  }
});
